name: ext-swoole_postgresql

on: [push, pull_request]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: phpswoole/swoole:latest-dev
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
    steps:
    - uses: actions/checkout@v1
    - name: install swoole
      run: php -m &&
        pwd
    - name: phpize
      run: phpize
    - name: build
      run: ./configure && make clean && make -j$(sysctl -n hw.ncpu)
    - name: install swoole_postgresql
      run: sudo make install &&
        sudo sh -c "echo 'extension=swoole_postgresql.so' >> /etc/php/7.4/cli/conf.d/30-swoole_postgresql.ini"
    - name: composer
      run: composer update
    - name: tests
      run: php vendor/bin/phpunit
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
